//
//  PostSampleData.swift
//  FacebookHomework
//
//  Created by Kong Vungsovanreach on 12/2/18.
//  Copyright © 2018 Kong Vungsovanreach. All rights reserved.
//

import UIKit
class PostSampleData {
    static var posts : [FacebookPost] = [
        FacebookPost(UIImage(named: "profile1")!, "Kong Vungsovanreach", "4hr", "Phnom Penh", "A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too A girl loves a boy,but he loves a boy A girl loves a boy,but he loves a boy too",nil, 972, 35, 98, true),
        FacebookPost(UIImage(named: "profile2")!, "Sreng Korn", "Dec 12", "Kompot", "Often, we are so shy or scared let out our feelings that we miss the chance to find out one true love. This short sad love story definitely revels upon the same. It is sometimes needed to take risks and let out your feelings as unsaid love is much more painful than unrequited love. So, grab your chance and tell that special person how much you love them!",UIImage(named: "profile5"), 11, 78, 23, false),
        FacebookPost(UIImage(named: "profile3")!, "Horn Kimheang", "9hr", "Koh Kong", "It is yet another example of what happens in love when you are too unsure to tell your feelings to the other person. It is a short sad love story that every teenager who had a crush can relate to. The pain and agony of your first love and the helplessness when you cannot share your feelings however much you try is something that is aptly narrated in these few lines.",UIImage(named: "profile2"), 145, 62, 33, false),
        FacebookPost(UIImage(named: "profile4")!, "Ren Rady", "5th Nov", "Kompong Cham", "It is a heart-wrenching short sad love story that narrates the pain of the partner who is left all alone as the other ceases to be. It gets so difficult to go on in life when your partner whom you loved so much is no more there. It is a simple yet sweet love story that reminds us that even death and separation is nothing when the love is true and it can still survive.",UIImage(named: "profile5"), 132, 32, 73, false),
        FacebookPost(UIImage(named: "profile5")!, "Sok Chakrey", "23rd Jul", "Siem Reab", "It is a short sad love story of the consequences and painful moments of reverie one faces after the couple has separated and decided to go on their own ways. You may let go of the relationship, delete the physical evidences but what about the memories?",UIImage(named: "profile4"), 551, 62, 93, false),
        FacebookPost(UIImage(named: "profile1")!, "Pheng Souphal", "6hr", "Takeo", "Sometimes, we need to take different paths, to meet expectations, to fulfil our responsibilities and to be something, and that may lead to the sacrifice of our love. But that does not make it any less beautiful or special for us.",UIImage(named: "profile1"), 661, 72, 83, false),
        FacebookPost(UIImage(named: "profile4")!, "Meas Marina", "2hr", "Singapor", "In this world of virtual reality, the scenario of love and relationships has turned false. Proposals on the social media, mushy updates and pictures, misunderstandings, break-ups and the awesome feature of blocking someone has seen much of love that has withered and died in vain.",UIImage(named: "profile3"), 551, 72, 93, false),
        FacebookPost(UIImage(named: "profile3")!, "Yon Yous", "8th Jan", "Thailand", "This short sad love story describes the impossible relationship of two people who love each other a lot but the circumstances prohibit them to be together. Yet, they are holding on and not letting their love go in vain.",nil, 132, 52, 33, true),
        FacebookPost(UIImage(named: "profile2")!, "Un Hongly", "6hr", "Syria", "There is no point in dragging on a relationship that is long dead. Separation from your partner is painful. But sometimes it can be liberating if you are suffocated in a relationship. Does not matter how good it was in the past.",nil, 155, 23, 35, true),
        FacebookPost(UIImage(named: "profile5")!, "Hol Bunhak", "12hr", "China", "It is a bereaved short sad love story of one partner waiting to join the other on the other side. But the dilemma and the loneliness that he/she feels here in this world makes the person sceptical about the next, where the beloved is waiting, or maybe not.",UIImage(named: "profile2"), 616, 72, 38, false),
        FacebookPost(UIImage(named: "profile1")!, "Pich Udom", "20hr", "Vietnam", "Once you are no longer a couple, the face of the lover fades away amidst strangers and there is no point in sorting things out. Sometimes all we need to do is let go.",nil, 661, 72, 93, true),
        FacebookPost(UIImage(named: "profile3")!, "Sorn Vengy", "Just Now", "Pursat", "I am afraid to sleep, afraid that your memory would haunt me in my dreams and when I do fall asleep, I trick myself to not wake up because I shall remember regretting the time I have left you.",UIImage(named: "profile1"), 175, 26, 37, false)
    ]
}
